version: 0.2 
 
phases: 
    install: 
        runtime-versions: 
            java: openjdk8 
         
    pre_build: 
        commands: 
            - echo pre-Build Phase Started at `date` 
            - mvn clean 
    build: 
        commands: 
            - echo build phase started at `date` 
            - mvn test 
    post_build: 
        commands: 
            - echo post-build phase started at `date` 
            - mvn package 
artifacts: 
    files: 
        - target/* 
    discard-paths: yes 
