apiVersion: v1
kind: Service
metadata:
  name: utd-nodePort-service
  labels: 
    app: usertimeline-deployment
    
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: usertimeline-deployment
